schema_version: "1.0"
mcp_name: "Egyptian Law MCP"
jurisdiction: "EG"

sources:
  - name: "Public Laws Portal"
    authority: "Ministry of Investment and Foreign Trade (Egypt)"
    official_portal: "https://portal.investment.gov.eg/publiclaws"
    retrieval_method: "HTML_INDEX + PDF_DOWNLOAD + PDF_TEXT_EXTRACTION + OPTIONAL_OCR"
    update_frequency: "weekly"
    last_ingested: "2026-02-22"
    license_or_terms:
      type: "Government Website Terms"
      url: "https://portal.investment.gov.eg/publiclaws"
      summary: "Legislation metadata and downloadable law PDFs published on official government domain."
    coverage:
      scope: "All discoverable Public Laws Portal legislation (categories discovered from /publiclaws/index; currently 16 and 17)"
      limitations: "Some PDFs are image-based and require OCR fallback; OCR-derived text may include recognition noise."
    languages:
      - "ar"
      - "en"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "2026-02-22"
